name: Build Module

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [14]
        os: [ ubuntu-22.04 ]
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: SetupNDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r24'
          add-to-path: true
           
      - name: Install cmake
        run: sudo snap install cmake --classic && sudo apt-get install -y clang-14 lld-14 llvm build-essential && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 14
      
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: jdk
          cache: gradle

      - name: Build release
        run: |
          chmod 777 ./build.sh && chmod +x ./build.sh && sed -i 's/\r$//' ./build.sh &&  ./build.sh
          
      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          mkdir upload
          mkdir release
          cp "safetynet-fix-v"*.zip ./upload/
          ReleaseName=`ls ./upload/safetynet-fix-v*.zip | awk -F '(/|.zip)' '{print $3}'` && echo "ReleaseName=$ReleaseName" >> $GITHUB_OUTPUT
          unzip "safetynet-fix-v"*.zip -d ./release
                
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.ReleaseName }}
          path: release
          if-no-files-found: error
          
