name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Check out
        uses: actions/checkout@v2
          
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: SetupNDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r21'
          
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build release
        run: |
          chmod 777 ./build.sh && chmod +x./build.sh && ./build.sh && mkdir ./upload && unzip -o ./*.zip -d ./upload >> $GITHUB_OUTPUT
          
      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          ReleaseName=`ls ./upload/safetynet-fix-*.zip | awk -F '(/|.zip)' '{print $3}'` && echo "ReleaseName=$ReleaseName" >> $GITHUB_OUTPUT
                
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
        name: ${{ steps.prepareArtifact.outputs.uReleaseName }}
        path: ./upload
