name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
       
      - name: Install tools
        run: |
            sudo apt-get update
            sudo apt-get -y install make build-essential cmake figlet clang ninja-build scons
            sudo apt-get -y upgrade
          
        
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: SetupNDK r24
        id: setup-ndk-r24
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
          local-cache: true
          
      - name: SetupNDK r25b
        id: setup-ndk-r25b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
          local-cache: true
          
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build release
        run: |
          chmod 777 ./build.sh
          chmod +x ./build.sh
          ./build.sh
          mkdir ./upload
          unzip -o ./safetynet-fix.zip -d ./upload

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: riru-safetynet-fix
          path: ./upload
          