name: Build Module

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
          java-package: jdk
          check-latest: true
          
      - name: SetupNDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r25b'
          add-to-path: true

      
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle
           
      - name: Install cmake
        run: sudo snap install cmake --classic && sudo snap install androidsdk

      - name: Update SDK
        run: sdkmanager "platform-tools" "platforms;android-33"
      
      - name: Build release
        run: |
          chmod 777 ./build.sh && chmod +x ./build.sh && ./build.sh
          
      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          mkdir upload
          mkdir release
          cp "safetynet-fix-v"*.zip ./upload/
          ReleaseName=`ls ./upload/safetynet-fix-v*.zip | awk -F '(/|.zip)' '{print $3}'` && echo "ReleaseName=$ReleaseName" >> $GITHUB_OUTPUT
          unzip "safetynet-fix-v"*.zip -d ./release
                
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.ReleaseName }}
          path: release
          if-no-files-found: error
          